#!/bin/bash
#PBS -N stat_dem_tcc
#PBS -l nodes=2:ppn=32
#PBS -j n
#PBS -l walltime=27:00:00

source /public/home/mfeng/anaconda3/etc/profile.d/conda.sh
conda activate geo

cd $PBS_O_WORKDIR

NP=`cat $PBS_NODEFILE | wc -l`

mpiexec -n $NP -hostfile $PBS_NODEFILE python 1_dem_tcc_mean.py -ta /public/home/mfeng/jwang/paper/10_ne/data/tasks/tasks.shp -i_tcc /public/home/mfeng/jwang/paper/10_ne/data/data_albers_tiles/result/tcc_mean -i_para /public/home/mfeng/jwang/paper/10_ne/data/data_albers_tiles/result/dem -mask /public/home/mfeng/jwang/paper/10_ne/data/shp/ne_albers.shp -o /public/home/mfeng/jwang/paper/10_ne/result/1_Spatial_distribution/reslut/dem/1_tiles