#!/bin/bash
#PBS -N loss_tiles
#PBS -l nodes=2:ppn=32
#PBS -j n
#PBS -l walltime=27:00:00
cd $PBS_O_WORKDIR

NP=`cat $PBS_NODEFILE | wc -l`

mpiexec -n $NP -hostfile $PBS_NODEFILE python 2_loss_albers_tiles.py -ta /public/home/mfeng/jwang/paper/10_ne/data/tasks/tasks.shp -tw /public/home/mfeng/jwang/paper/data/shp/task/tasks_albers.shp -i /public/home/mfeng/work/test/forest/pangyong/phase2/ne/forest/file66/scene02/comp02/change0a/r01/data -o /public/home/mfeng/jwang/paper/10_ne/data/data_albers_tiles/result/loss