#!/bin/bash
#PBS -N extract_TCC
#PBS -l nodes=1:ppn=2
#PBS -j n
#PBS -l walltime=27:00:00

source /public/home/mfeng/anaconda3/etc/profile.d/conda.sh
conda activate geo

cd $PBS_O_WORKDIR

NP=`cat $PBS_NODEFILE | wc -l`

mpiexec -n $NP -hostfile $PBS_NODEFILE python 1_extract_tcc.py -i_tcc /public/home/mfeng/cwang/work/test/Himalaya/file01/scene01/comp01/data -i_csv /public/home/mfeng/jwang/1_github/2_extract/data -o /public/home/mfeng/jwang/1_github/2_extract/result -ta /public/home/mfeng/cwang/work/test/Himalaya/file01/scene01/comp01/tasks.shp